export const Apartments = [
  {
    name: "Apartment 01",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371052/apartment/pexels-emre-can-acer-2079246_f4psu1.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 02",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371047/apartment/ralph-ravi-kayden-FqqiAvJejto-unsplash_pdqf1j.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 03",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371047/apartment/pexels-sharath-g-2251247_n7qu2o.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 04",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371046/apartment/pexels-john-tekeridis-1428348_lxfu6t.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 05",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371046/apartment/pexels-vecislavas-popa-1668860_hoty2x.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 06",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371045/apartment/point3d-commercial-imaging-ltd-Cu2xZLKgn10-unsplash_o6nnod.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 07",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371044/apartment/pexels-homelane-com-1776574_yzwvcl.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 08",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371043/apartment/francesca-tosolini-tHkJAMcO3QE-unsplash_uh7yfv.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 09",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371042/apartment/pexels-pixabay-275484_xynrjc.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 10",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371042/apartment/pexels-pixabay-276554_kli8zv.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 11",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371040/apartment/huy-nguyen-AB-q9lwCVv8-unsplash_jjyluh.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 12",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371040/apartment/pexels-terry-magallanes-2635038_q0rajh.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 13",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371039/apartment/brandon-griggs-wR11KBaB86U-unsplash_ugklvc.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 14",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371038/apartment/jarek-ceborski-jn7uVeCdf6U-unsplash_feus9z.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 15",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371037/apartment/pexels-expect-best-323780_xsyhw9.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 16",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371037/apartment/pexels-pixabay-265004_st2a2b.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 17",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371036/apartment/deborah-cortelazzi-gREquCUXQLI-unsplash_uhpwdx.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 18",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371034/apartment/patrick-perkins-iRiVzALa4pI-unsplash_kcujfv.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 19",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371034/apartment/pexels-pixabay-271618_nlwayy.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 20",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371034/apartment/naomi-hebert-MP0bgaS_d1c-unsplash_sxo0ov.jpg",
    category: "omg",
    liked: false,
  },
  {
    name: "Apartment 21",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371034/apartment/patrick-perkins-3wylDrjxH-E-unsplash_vq8qjx.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 22",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371033/apartment/pexels-vecislavas-popa-1643384_w5nec3.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 23",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371032/apartment/pexels-vecislavas-popa-1743227_ipfe8w.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 24",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371032/apartment/pexels-vecislavas-popa-813692_gr5osf.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 25",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371032/apartment/pexels-pixabay-271816_tutcfg.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 26",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371031/apartment/pexels-pixabay-259962_arimbw.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 27",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371031/apartment/pexels-mark-mccammon-2724749_vbghwn.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 28",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371030/apartment/pexels-igor-starkov-1693946_gtictq.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 29",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371029/apartment/pexels-vecislavas-popa-1571472_gqsdgh.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 30",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371029/apartment/pexels-pixabay-462235_c8e6aj.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 31",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371028/apartment/pexels-jean-van-der-meulen-1454805_nqaepl.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 32",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371028/apartment/pexels-expect-best-323772_ygkwyi.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 33",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371028/apartment/pexels-naim-benjelloun-2030037_r9fez9.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 34",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371027/apartment/pexels-expect-best-323776_xjy1la.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 35",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371027/apartment/pexels-fox-1595589_u5vyqa.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 36",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371027/apartment/pexels-expect-best-323775_piuc7u.jpg",
    category: "shared",
    liked: false,
  },
  {
    name: "Apartment 37",
    url: "https://res.cloudinary.com/jewbreel1/image/upload/v1666371027/apartment/pexels-victoria-akvarel-1648771_tvdtzt.jpg",
    category: "shared",
    liked: false,
  },
];
